name: Meetup DotNet And Docker (CI)
on:
 #push:
    #branches: [ main ]
  #pull_request:
   # branches: [ main ]
  workflow_dispatch: 
jobs:

  build:

    runs-on: ubuntu-latest  #Exécuter les actions sur un agent Linux

    steps:
    - uses: actions/checkout@v2   #Récupère le code source à partir du repository github
    - name:  Récupère .NET
      uses: actions/setup-dotnet@v1 
      with:
          dotnet-version: 5.0.x            
    - name: Publier le code source
      run:  dotnet publish -c release ./app/DotNetAndDocker.csproj -o ./app/publier      
    - name: Tester le code
      run:  echo "Il faudrait tester le code !!"
    - name: Construire image Docker      
      run:  docker build . --file ./app/Dockerfile --tag dotnetandocker:v1
      uses: Azure/login@v1
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{secrets.AZURE_CREDENTIALS}}