name: Docker Image CI

on:
 # push:
 #   branches: [ main ]
  #pull_request:
   # branches: [ main ]
  workflow_dispatch: 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2   #Récupère le code source à partir du repository github
    - name:  Récupère .NET
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: 5.0.x        
    - name: Restorer les dépendances
      run: dotnet restore
    - name: Publier le code source
      run:  dotnet publish -c Release -o .\publier
    - name: Tester le code
      run: echo "Il faudrait tester le code !!"
    - name: Construire image Docker
      run: docker build . --file Dockerfile --tag dotnetandocker:v1
