name: Meetup DotNet And Docker 
on:
 push:
    branches: [ main ]
  #pull_request:
   # branches: [ main ]
  #workflow_dispatch: 

env:
  RG_NAME: meetup-rg
  ACR_NAME: acrmeeetup42
  IMAGE_NAME: ${{ github.repository }}  
  ACR_SERVER: acrmeeetup42.azurecr.io

jobs:

  build:

    runs-on: ubuntu-latest  #Exécuter les actions sur un agent Linux
    
    steps:

    - uses: actions/checkout@v2   
    - name:  Récupère .NET
      uses: actions/setup-dotnet@v1 
      with:
          dotnet-version: 5.0.x            
    - name: Publier le code source
      run:  
        dotnet publish -c release ./app/DotNetAndDocker.csproj -o ./app/publier      
    - name: Tester le code
      run:  echo "Il faudrait tester le code !!"
    - name: Connexion à Azure Container Registry
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: ${{ env.ACR_SERVER }}
        username: ${{ env.ACR_NAME }}
        password: ${{ secrets.PASSREGISTRY }}
    - name: Extraire les métadonnées docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.ACR_SERVER }}/${{ env.IMAGE_NAME }}
    - name: Construire et pousser image Docker
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

