name: Meetup DotNet And Docker 
on:
 #push:
    #branches: [ main ]
    
  #pull_request:
   # branches: [ main ]
  workflow_dispatch: 

env:
  RG_NAME: meetup-rg
  ACR_NAME: meetup42acr
  IMAGE_NAME: dotnetanddocker
  ACR_SERVER: meetup42acr.azurecr.io

jobs:

  build:

    runs-on: ubuntu-latest  
    
    steps:

    - uses: actions/checkout@v2   
    - name:  Récupère .NET
      uses: actions/setup-dotnet@v1 
      with:
          dotnet-version: 5.0.x            
    - name: Publier le code source
      run:  
        dotnet publish -c release ./app/dotnetanddocker.csproj -o ./app/publier      
    - name: Tester le code
      run:  | 
            echo "Il faudrait tester le code !!"            
    - name: Connexion à Azure Container Registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ env.ACR_SERVER }}
        username: ${{ env.ACR_NAME }}
        password: ${{ secrets.PASSREGISTRY }}
    - name: Extraire les métadonnées docker
      id: meta
      uses: docker/metadata-action@v3.5.0
      with:
        images: ${{ env.ACR_SERVER }}/${{ env.IMAGE_NAME }} 
        tags: |
         type=semver,pattern={{version}},value=v1.0.0
         
    - name: Construire et pousser image Docker
      uses: docker/build-push-action@v2.7.0
      with:         
          context: ./
          file: ./app/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}   
     